### ISSUE TITLE
Como é este sistema?

### ISSUE THREAD

**Issue by alexandre-mbm** [interlegis/spdo#1]
Há screenshot ou documentação mostrando ele em funcionamento?

**Comment by lepri** [comment]
Olá Alexandre,

No Colab existe uma página de documentação do SPDO[1]. Nela existem vídeos
que mostram o funcionando do sistema.

[]'s
Gustavo Lepri


[1] https://colab.interlegis.leg.br/wiki/SPDO

2015-02-14 10:15 GMT-02:00 Alexandre Magno <notifications@github.com>:

> Há screenshot ou documentação mostrando ele em funcionamento?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/interlegis/spdo/issues/1>.
>



-- 
Gustavo Lepri

**Comment by rougeth** [comment]
@alexandre-mbm esse é uma nova versão do SPDO que está sendo desenvolvida. Na verdade ele esta sendo reescrito em Django/Python, as funcionalidades continuarão as mesmas, ou serão melhoradas.

**Comment by alexandre-mbm** [comment]
Assisti alguns vídeos. Obrigado a todos que me responderam.
